name: dvm
description: A simple CLI to manage Dart SDK versions per project.
version: 1.0.0
homepage: https://github.com/blendthink/dvm

environment:
  sdk: ^3.0.7

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  test: ^1.24.6
