name: cli
description: A library to easily create a command-line app
version: 1.0.0
homepage: https://github.com/blendthink/dvm/tree/main/packages/cli

environment:
  sdk: ^3.0.7

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  test: ^1.24.6
